[project]
name = 'decentralized-fitness-tracker-contract'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.decentralized-fitness-tracker-contract]
path = 'contracts/decentralized-fitness-tracker-contract.clar'

epoch = 3.1
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false

[repl.remote_data]
enabled = false
api_url = 'https://api.hiro.so'
